[package]
name = "festy"
version = "0.1.0"
edition = "2021"
author="Sohn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"